Epoch 1/5:   0%|                                                                                                                                              | 0/283 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "c:\Users\AMI-DEEP3\Desktop\younguk\Pytorch-UNet-master\Pytorch-UNet-master\train.py", line 140, in <module>
    train_model(
  File "c:\Users\AMI-DEEP3\Desktop\younguk\Pytorch-UNet-master\Pytorch-UNet-master\train.py", line 89, in train_model
    loss = criterion(masks_pred, true_masks)
  File "c:\Users\AMI-DEEP3\anaconda3\envs\younguks\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\AMI-DEEP3\anaconda3\envs\younguks\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\Users\AMI-DEEP3\anaconda3\envs\younguks\lib\site-packages\torch\nn\modules\loss.py", line 1293, in forward
    return F.cross_entropy(
  File "c:\Users\AMI-DEEP3\anaconda3\envs\younguks\lib\site-packages\torch\nn\functional.py", line 3479, in cross_entropy
    return torch._C._nn.cross_entropy_loss(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument target in method wrapper_CUDA__nll_loss2d_forward)
